apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: highscore
    app.kubernetes.io/component: highscore
    app.kubernetes.io/instance: highscore
  name: highscore
  namespace: arcade
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: highscore
  strategy:
    type: Recreate # Changed from RollingUpdate to prevent automatic recreation
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        deployment: highscore
    spec:
      restartPolicy: Never # Added to prevent automatic restarts
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/arcade/highscore
        imagePullPolicy: IfNotPresent
        name: highscore
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/db
          name: highscore-data
      volumes:
      - name: highscore-data
        persistentVolumeClaim:
          claimName: highscore-data